config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root to: 'marketing#index'

  get '/checkpoints', to: redirect('/archives')
  get '/checkpoints/:id', to: redirect('/archives/%{id}')

  resources :marketing, only: [:index]
  resources :tasks, only: [:index, :show, :destroy]
  resources :checkpoints, :path => :archives, only: [:index, :show]
  resources :users, only: [:edit, :update]

  ActiveAdmin.routes(self)
  devise_for :users

  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  namespace :api do
    resources :checkpoints, only: [:index, :show] do
      resources :tasks, only: [:index]
    end
    resources :tasks, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :analytics
      end
      member do
        get :analytics
        post :complete
        post :reopen
      end
    end
  end
end

app/views/layouts/application.html.haml
!!! Strict
%html{:xmlns => "http://www.w3.org/1999/xhtml", :itemtype => "http://schema.org/Event"}
  %head
    %meta{charset: "utf-8"}
    %meta{'http-equiv': "X-UA-Compatible", 'content': "IE=edge"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title cueDO - Work Smarter. Do MORE
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    %link{href: "https://fonts.googleapis.com/css?family=Roboto+Slab", rel: "stylesheet"}
    %link{href: "https://fonts.googleapis.com/css?family=Fredoka+One", rel: "stylesheet"}
    = favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon"
    %link{:href => "favicons/apple-touch-icon-57x57.png", :rel => "apple-touch-icon-precomposed", :sizes => "57x57"}/
    %link{:href => "favicons/apple-touch-icon-114x114.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
    %link{:href => "favicons/apple-touch-icon-72x72.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
    %link{:href => "favicons/apple-touch-icon-144x144.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
    %link{:href => "favicons/apple-touch-icon-60x60.png", :rel => "apple-touch-icon-precomposed", :sizes => "60x60"}/
    %link{:href => "favicons/apple-touch-icon-120x120.png", :rel => "apple-touch-icon-precomposed", :sizes => "120x120"}/
    %link{:href => "favicons/apple-touch-icon-76x76.png", :rel => "apple-touch-icon-precomposed", :sizes => "76x76"}/
    %link{:href => "favicons/apple-touch-icon-152x152.png", :rel => "apple-touch-icon-precomposed", :sizes => "152x152"}/
    %link{:href => "favicons/favicon-196x196.png", :rel => "icon", :sizes => "196x196", :type => "image/png"}/
    %link{:href => "favicons/favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
    %link{:href => "favicons/favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %link{:href => "favicons/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %link{:href => "favicons/favicon-128.png", :rel => "icon", :sizes => "128x128", :type => "image/png"}/
    %meta{:content => "cueDO", :name => "application-name"}/
    %meta{:content => "#FFFFFF", :name => "msapplication-TileColor"}/
    %meta{:content => "favicons/mstile-144x144.png", :name => "msapplication-TileImage"}/
    %meta{:content => "favicons/mstile-70x70.png", :name => "msapplication-square70x70logo"}/
    %meta{:content => "favicons/mstile-150x150.png", :name => "msapplication-square150x150logo"}/
    %meta{:content => "favicons/mstile-310x150.png", :name => "msapplication-wide310x150logo"}/
    %meta{:content => "favicons/mstile-310x310.png", :name => "msapplication-square310x310logo"}/

    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      %script{src: "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"}
      %script{src: "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"}

  %body{'ng-app' => "application"}
    .container
      - if current_user.blank?
        .row
          .col-4.mx-auto
            = image_tag "cueDO-logo-dark-background-p-500.png", class: 'img-fluid'
            %br
            %br
      - else
        .row
          .col-lg-8.mx-auto
            %nav.navbar
              .col-12.col-lg-4.mx-auto.text-center
                = link_to tasks_url, class: "navbar-brand" do
                  = image_tag "cueDO-logo-dark-background-p-500.png"
                %br
                %br
              .col-12.col-lg-8.mx-auto
                %ul.nav.justify-content-center
                  - if current_user.admin?
                    %li.nav-item.d-none.d-sm-block
                      = link_to "👁‍🗨", admin_dashboard_path, title: "Admin", class: "nav-link"
                  %li.nav-item
                    = link_to "⚙️", edit_user_path(:current_user), title: "Account Settings", class: "nav-link"
                  %li.nav-item
                    = link_to checkpoints_path, title: "Meals Provided", class: "btn btn-yellow nav-link" do
                      🍽
                      %span.badge.badge-light.user-donation-amount= current_user.donation_amount
                  &nbsp;
                  %li.nav-item
                    = link_to checkpoints_path, title: "Productivity Score", class: "btn btn-navy-blue nav-link" do
                      📆
                      %span.badge.badge-light= number_to_human current_user.tasks.sum(:points)
                %br

      = yield
    = Gon::Base.render_data
    = javascript_include_tag 'application'

app/views/layouts/marketing.html.haml
!!! Strict
%html{:xmlns => "http://www.w3.org/1999/xhtml", :itemtype => "http://schema.org/Event"}
  %head
    %meta{charset: "utf-8"}
    %meta{'http-equiv': "X-UA-Compatible", 'content': "IE=edge"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title cueDO - Work Smarter. Do MORE
    = csrf_meta_tags
    = stylesheet_link_tag 'marketing', media: 'all'
    %link{href: "https://fonts.googleapis.com/css?family=Roboto+Slab", rel: "stylesheet"}
    %link{href: "https://fonts.googleapis.com/css?family=Fredoka+One", rel: "stylesheet"}
    = favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon"

    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      %script{src: "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"}
      %script{src: "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"}

  %body{'ng-app' => "application"}
    .container
      = yield
    = Gon::Base.render_data
    = javascript_include_tag 'application'